blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://zonfig.dev/docs
    about: Check the documentation for usage guides
  - name: Discussions
    url: https://github.com/groschi24/zonfig/discussions
    about: Ask questions and discuss ideas
